server:
  port: 7001

spring:
  datasource:
    url: jdbc:mysql://150.158.197.108:3306/gmall_product?useSSL=false&charcterEncoding=utf-8
    username: root
    password: cdy1998930!
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
minio:
  endPoint: http://150.158.197.108:9000
  username: admin
  password: admin123456
  bucketName: gmall-res